////////////////////////////////////////////////////////////////////////////
//
//	Copyright (c) Unpublished Work of Novell, Inc.  All rights reserved.
//
//	THIS WORK IS AN UNPUBLISHED WORK AND CONTAINS CONFIDENTIAL,
//	PROPRIETARY, AND TRADE SECRET INFORMATION OF NOVELL, INC.
//	ACCESS TO THIS WORK IS RESTRICTED TO (I) NOVELL EMPLOYEES WHO HAVE
//	A NEED TO KNOW TO PERFORM THEIR TASKS WITHIN THE SCOPE OF
//	THEIR ASSIGNMENTS AND (II) ENTITIES OTHER THAN NOVELL WHO HAVE
//	ENTERED INTO APPROPRIATE LICENCE AGREEMENTS.  NO PART OF THIS
//	WORK MAY BE USED, PRACTICED, PERFORMED, COPIED, DISTRIBUTED,
//	REVISED, MODIFIED, TRANSLATED, ABRIDGED, CONDENSED, EXPANDED,
//	COLLECTED, COMPILED, LINKED, RECAST, TRANSFORMED, OR ADAPTED
//	WITHOUT THE PRIOR WRITTEN CONSENT OF NOVELL.  ANY USE OR
//	EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT
//	THE PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.
//
//--------------------------------------------------------------------------
//
// FILE:
//
// AUTHOR:
//
// DESCRIPTION:
//
// CHANGES:
//
////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////
//
//	"flag_rsc.h"
//
// Header file with the flag resource constants
//
////////////////////////////////////////////////////////////////////////////

#ifndef __FLAG_RSC_H	// prevent multiple includes
#define __FLAG_RSC_H


// Resource Objects ////////////////////////////////////////////////////////

#define	FLAGDIALOG					1000
#define	FLAGICON						2000

// Flag Dialog Constants ///////////////////////////////////////////////////

// radio button controls
#define	IDD_SET							100
#define	IDD_CLEAR						101

#define	IDD_AFTERCHAIN			120
#define	IDD_INTERRUPT				121

// text edit controls
#define	IDD_SETTEXT					110
#define	IDD_CLEARTEXT				111
#define IDC_GROUPBOX1	102
#define IDC_GROUPBOX2	103
#define IDC_GROUPBOX3	104

// static text controls

// standard button controls
#define	IDOK								1
#define IDCANCEL						2
#define IDHELP							998

////////////////////////////////////////////////////////////////////////////

#endif	// #ifndef __FLAG_RSC_H
