#ifndef T_DIALOG_H
#define T_DIALOG_H

#define TEXT_SETUP_DIALOG		100

#define ST_OBJECTNAME				1001  //The name of the object type being edited

#define ED_TITLE	7
#define CB_HORZSCROLL       1105
#define CB_VERTSCROLL       1106
#define PB_OK               1
#define PB_CANCEL           2
#define PB_HELP							3
#define ST_LABEL_LINE	1004

#define ED_LIMIT            1300
#define CB_EDITABLE					1301
#define CB_FRAME		        1302
#define CB_USESENTER				1303
#define CB_USESTAB					1304
#define RB_LEFT             1305
#define RB_CENTER           1306
#define RB_RIGHT            1307
#define RB_CASEINSENSITIVE  1308
#define RB_UPPERCASE        1309
#define RB_LOWERCASE        1310
#define PB_FONTS						1312
#define ED_TABSIZE					1315
#define CB_SELECTALL				1316
#define RB_MULTILINE				1317
#define RB_SINGLELINE				1318
#define RB_STATIC						1319
#define CB_PASSWORD					1320
#define ST_JUSTIFICATION		1321
#define STR_FRAME						1322
#define STR_FRAMEANDBACK		1323
#define CB_KEEPSELECTION		1324
								
#define ST_LABEL_TEXT						1400
#define ST_LABEL_LIMIT					1401
#define ST_LABEL_WIDTH					1402
#define ST_LABEL_SIZEOPTIONS		1403
#define ST_LABEL_CASE						1404
#define ST_LABEL_TYPE						1405
#define ST_LABEL_STYLE					1406
#define ST_VERTLINE							1407
#define IDC_GROUPBOX2	1002
#define IDC_RADIOBUTTON2	1002
#define IDC_RADIOBUTTON1	1002
#define IDC_CHECKBOX1	1004
#define IDC_GROUPBOX1	1002
#define ST_HORZLINE1						1408
#define ST_HORZLINE2						1409

#endif

