
LONG CreateDateObject(OBJECTID oiDate, AObjMessage* theSystem);
LONG AssignDateObject(OBJECTID oiDate, AObjMessage* theSystem);
LONG ValidateDateObject(OBJECTID oiDate);
LONG ReadObject(OBJECTID oiDate);
LONG CheckObject(void);
LONG BuildDateSignal(OBJECTID oiDate, AObjMessage* theSystem);
LONG QueryProtocol(AObjMessage* theSystem);
LONG ExportDateObject(OBJECTID oiDate);
LONG ImportDateObject(OBJECTID oiDate);



	
