#define  idx_contents		1000
#define  idx_introduction_to_the_text_alm		0x54657874	/*Text*/
#define  idx_editing_the_text_object		3000
#define  idx_text_object_signals		1003
#define  idx_text_alm_functions		1004
#define  idx_entering_default_text		1005
#define  idx_specifying_size_options		1006
#define  idx_specifying_case__windows		1007
#define  idx_specifying_a_type		1008
#define  idx_setting_style_options__windows		1009
#define  idx_specifying_justification		1011
#define  idx_setting_attributes		1012
#define  idx_append_return	0x74586172	/*tXar*/
#define  idx_append_tab		0x74586174	/*tXat*/
#define  idx_clear_text		0x7458636C	/*tXcl*/
#define  idx_compare_text		0x7458636D	/*tXcm*/
#define  idx_concatenate		0x7458636E	/*tXcn*/
#define  idx_find_replace		0x74586672	/*tXfr*/
#define  idx_get_field		0x74586766	/*tXgf*/
#define  idx_get_line		0x7458676C	/*tXgl*/
#define  idx_get_number		0x7458676E	/*tXgn*/
#define  idx_get_word		0x74586777	/*tXgw*/
#define  idx_insert_text		0x74586974	/*tXit*/
#define  idx_intersect_text		0x74587874	/*tXxt*/
#define  idx_left_text		0x74586C73	/*tXls*/
#define  idx_load_text_file	0x74586C74	/*tXlt*/
#define  idx_merge_text		0x7458756E	/*tXun*/
#define  idx_mid_text		0x74586D73	/*tXms*/
#define  idx_omit_text		0x74586F6D	/*tXom*/
#define  idx_right_text		0x74587273	/*tXrs*/
#define  idx_save_text_file	0x74587374	/*tXst*/
#define  idx_text_font_size	0x74586673	/*tXfs*/
#define  idx_text_length		0x74586C6E	/*tXln*/
#define  idx_uppercase		0x74587563	/*tXuc*/
#define  idx_usage_clear_text		1040
#define  idx_usage_compare_text		1043
#define  idx_usage_concatenate		1046
#define  idx_usage_find_replace		1049
#define  idx_usage_get_field		1052
#define  idx_usage_get_line		1055
#define  idx_usage_get_number		1058
#define  idx_usage_get_word		1061
#define  idx_usage_intersect_text		1066
#define  idx_usage_left_text		1069
#define  idx_usage_load_text_file		1072
#define  idx_usage_merge_text		1075
#define  idx_usage_mid_text		1078
#define  idx_usage_omit_text		1081
#define  idx_usage_right_text		1084

