#define  idx_introduction_to_the_notification_alm		0x4E746679	/*Ntfy*/
#define  idx_editing_the_notification_object		3000
#define  idx_notification_object_signals		1003
#define  idx_notification_alm_functions		1004
#define  idx_alert_notify		0x6E416C74	/*nAlt*/
#define  idx_usage_alert_notify		1007
#define  idx_start_notify		0x6E537474	/*nStt*/
#define  idx_usage_start_notify		1010
#define  idx_stop_notify		0x6E537470	/*nStp*/
#define  idx_usage_stop_notify		1013
#define  idx_contents		1000

