///////////////////////////////////////////////////
//This file just contains a list of all the files
//the polybutton object includes
///////////////////////////////////////////////////

#define ASTRICT
#define STRICT

#include <alloc.h>
#include <ctype.h>
#include "windows.h"
#include "stddef.h"
#include "mem.h"
#include "string.h"

#include "a_alm.h"
#include "a_almutl.h"
#include "intdebug.h"
#include "ap_macro.h"
#include "op_wnd.h"
#include "o_wnd.h"
#include "o_text.h"
#include "o_number.h"

#include "data.h"
#include "globals.h"
#include "strings.h"
#include "macros.h"
#include "vi.h"
#include "utils.h"
#include "dialog.h"
