#include "helpids.h"

#ifndef L_DIALOG_H
#define L_DIALOG_H

#define LIST_SETUP_DIALOG		100

#define ST_OBJECTNAME				1001  //The name of the object type being edited


#define PB_OK								IDOK
#define PB_CANCEL						IDCANCEL
#define LB_ITEMS						200
#define	LB_OBJECTS        	201
#define PB_ADD            	202
#define PB_REMOVE         	203
#define PB_FONTS						204
#define LB_STARTUPLIST			205
#define DD_TEXTOBJECTS			206
#define CB_MULTISELECT			207
#define ST_ENTRY						208
#define ED_ENTRY						209

#define RB_LISTBOX					210
#define RB_SIMPLECOMBO 			211
#define RB_DROPDOWNCOMBO		212
#define RB_DROPDOWNLIST			213

#define PB_HELP							214


#endif

