#define  idx_contents		1000
#define  idx_introduction_to_the_menu_alm		0x4D656E75	/*Menu*/
#define  idx_editing_the_menu_object		3000
#define  idx_menu_object_signals		1003
#define  idx_menu_alm_functions		1004
#define  idx_menu_components		1005
#define  idx_menu_assignments		1006
#define  idx_text_only_menu_items		1007
#define  idx_naming_the_menu		1008
#define  idx_specifying_display_options		1009
#define  idx_adding_and_removing_menu_items		1010
#define  idx_editing_objects_in_the_menu		1011
#define  idx_specifying_the_menu_type		1012
#define  idx_specifying_the_startup_status		1013
#define  idx_getting_the_text_of_a_menu_item_selection		1014
#define  idx_getting_the_index_of_a_menu_item_selection		1015
#define  idx_count_menu_items		0x6D436E74	/*mCnt*/
#define  idx_delete_menu_item		0x6D44656C	/*mDel*/
#define  idx_disable_menu		0x6D447362	/*mDsb*/
#define  idx_enable_menu			0x6D456E62	/*mEnb*/
#define  idx_get_item_title		0x6D476974	/*mGit*/
#define  idx_get_popup_item		0x6D477070	/*mGpp*/
#define  idx_insert_menu_item		0x6D496E73	/*mIns*/
#define  idx_set_item_title			0x6D52746C	/*mRtl*/
#define  idx_set_popup_item		0x6D537070	/*mSpp*/

