#ifndef L_STRING_H
#define L_STRING_H

#define ERR_NULL_PTR									2 // "NULL pointer in %s line #%d"
#define ERR_INVALIDWINDOW							3 //"Invalide window handle in %s line #%d"
#define ERR_WRONG_TYPEID							4 //"Incorrect typeid in %s line #%d"
#define ERR_GET_PARAMETER_FAILED			5 //"Unable to get function parameter in %s line #%d"
#define ERR_CREATING_PSUEDO_OBJECT		6 //Unable to create psuedo object in %s line #%d"

#endif
