#define  idx_contents		1000
#define  idx_introduction_to_the_date_alm		0x44617465	/*Date*/
#define  idx_editing_the_date_object		3000
#define  idx_entering_a_default_date		1003
#define  idx_specifying_a_display_style		1004
#define  idx_setting_options		1005
#define  idx_display_options		1006
#define  idx_option_checkboxes		1007
#define  idx_setting_attributes		1008
#define  idx_date_object_signals		1009
#define  idx_date_alm_functions		1010
#define  idx_change_date		0x694E6474	/*iNdt*/
#define  idx_compare_dates		0x634D6474	/*cMdt*/
#define  idx_date_difference		0x64546466	/*dTdf*/
#define  idx_date_font_size		0x64546673	/*dTfs*/
#define  idx_usage_date_font_size		1021
#define  idx_parse_date		0x64546272	/*dTbr*/
#define  idx_usage_parse_date		1024
#define  idx_current_date		0x63526474	/*cRdt*/

