#ifndef TM_DIALG_H
#define TM_DIALG_H


/// Define for dialog ID's ////

#define TIME_SETUP_DIALOG			106

#define ST_OBJECTNAME				1001  //The name of the object type being edited

/// Defines for controls ////
#define ED_TITLE						1100
#define PB_OK               1
#define PB_CANCEL           2
#define PB_HELP							3

#define CB_EDITABLE					1301
#define CB_FRAME		        1302
#define PB_FONTS						1312
#define CB_SELECTALL				1316
#define CB_ACTIVATABLE			1319
#define CB_CANACTIVATE			1319
#define CB_DISPLAYEMPTY	    1320

#define RB_KEEPCURRENT 			1422
#define RB_EDITABLE					1423
#define RB_NEITHER					1424

#define CB_SECONDS					1440
#define RB_24HOUR						1441
#define RB_12HOUR						1442
#define RB_DEFHOUR					1443

#endif

