/*//////////////////////////////////////////////////////////////
//
//	Copyright (c) Unpublished Work of Novell, Inc.  All rights reserved.
//
//	THIS WORK IS AN UNPUBLISHED WORK AND CONTAINS CONFIDENTIAL,
//	PROPRIETARY, AND TRADE SECRET INFORMATION OF NOVELL, INC.
//	ACCESS TO THIS WORK IS RESTRICTED TO (I) NOVELL, INC. EMPLOYEES
//	WHO HAVE A NEED TO KNOW HOW TO PERFORM THEIR TASKS WITHIN THE SCOPE
//	OF THEIR ASSIGNMENTS AND (II) ENTITIES OTHER THAN NOVELL, INC. WHO
//	HAVE ENTERED INTO APPROPRIATE LICENSE AGREEMENTS.  NO PART OF THIS
//	WORK MAY BE USED, PRACTICED, PERFORMED, COPIED, DISTRIBUTED,
//	REVISED, MODIFIED, TRANSLATED, ABRIDGED, CONDENSED, EXPANDED,
//	COLLECTED, COMPILED, LINKED, RECAST, TRANSFORMED, OR ADAPTED
//	WITHOUT THE PRIOR WRITTEN CONSENT OF NOVELL, INC.  ANY USE OR
//	EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT
//	THE PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.
//
//--------------------------------------------------------------
//
// FILE: tm_str.cpp
//
// AUTHOR: Ksai Liang
//
// DESCRIPTION:	String Definition
//
// CHANGES:
//
//////////////////////////////////////////////////////////////*/
#ifndef TM_STR_H
#define TM_STR_H

#define ERR_NULL_TIME										2 	//"NULL num pointer in %s"
#define ERR_NULL_HTI										4 	//"NULL hni pointer in %s"
#define ERR_WRONG_TYPEID								7 		//"Incorrect Object Type in %s"
#define ERR_INVALIDWINDOW								15	//"Invalid window handle in %s"

#define WARN_CANNOT_CHANGE_TYPE					16  //"Can only change the type of temporary number objects"

#define	ERR_GET_PARAMETER_FAILED				17	// "Unable to get parameter #%d in %s"
#define	ERR_CREATING_PSUEDO_OBJECT			18	// "Unable to create pseudo object %s"

#endif

