////////////////////////////////////////////////////////////////////////////
//	This file contains the defines for menu item and control ids.
////////////////////////////////////////////////////////////////////////////

#ifndef __RESCONST_H__
#define __RESCONST_H__

#define	WINDOWS_MENU_POSITION	2

// defines for items in the "File" popup

#define IDM_NEW         101
#define IDM_OPEN        102
#define IDM_CLOSE       103
#define IDM_SAVE        104
#define IDM_SAVEAS      105
#define IDM_QUIT        110
#define IDM_ABOUT       111
#define IDM_EDITCONFIG  112
#define IDM_WRITE       113
#define IDM_WRITEBMP    114

//defines for items in Edit Menu

#define IDM_UNDO  		 			121
#define IDM_CUT        			122
#define IDM_COPY       			123
#define IDM_PASTE      			124
#define IDM_DELETE     			125
#define IDM_EDITCOMP	 			126
#define IDM_NEWCOMP		 			127
#define IDM_REPLACEDLL 			128
#define IDM_REPLACEHELPFILE 129

// defines for items in the "Window" popup

#define IDM_TILE        151
#define IDM_CASCADE			152

// defines for the icon editor menu

#define IDM_IMPORT			204
#define IDM_SAVEICON		201
#define IDM_CLEARICON   202
#define IDM_RESTOREICON 203

// other defines


#define IDM_FIRSTCHILD	300

#define ID_NEWNAME		104
#define ID_STATICTEXT	106

#define ID_OK			100
#define ID_CANCEL		102


// defines for string resources

#define STR_APPNAME	211
#define STR_PROJECTNAME	212
#define STR_SUBJECTNAME 213
#define STR_NAVIGATOR	214

#define PALETTEHEIGHT 91

//bitmap ID's
#define IDBMP_4BIT_SPLASH 3000
#define IDBMP_8BIT_SPLASH 3002

#endif
