#define  idx_contents		1000
#define  idx_introduction_to_the_text_builder_alm		0x54666374	/*Tfct*/
#define  idx_editing_the_text_builder_object		3000
#define  idx_linking_variables_to_objects		1003
#define  idx_editing_expression_objects		1004
#define  idx_selecting_a_result_object		1005
#define  idx_defining_an_expression		1006
#define  idx_using_auto_update		1007
#define  idx_text_builder_object_signals		1008
#define  idx_text_builder_functions		1009
#define  idx_auto_update_off		0x74416F66	/*tAof*/
#define  idx_auto_update_on		0x74416F6E	/*tAon*/
#define  idx_make_text		0x7446636C	/*tFcl*/
#define  idx_set_expression		0x74467374	/*tFst*/

