#define PG_DIALG_H
#ifdef  PG_DIALG_H

#define OBJECTNAMESIZE	  35
#define IDD_OBJECT			  201
#define PAGEDIALOG      	100

#define	HELPFILE				"serhelp.hlp"

#define PAGEOK        	  1
#define PAGECANCEL    	  2
#define PAGEHELP      	998
#define PAGEADD     		101
#define PAGEEDIT    		102
#define PAGEREMOVE  		103
#define PAGEAVAIL   		104
#define PAGESELECT  		105
#define PAGEGRID        106
#define PAGELAYOUT      107
#define PAGELOUT				111

#endif
