/*--------------------------------------------------------------------------*/
/* Boole.H: Header file of boolean type.                                    */
/* Serius Corporation, August 25, 1992.                                     */
/*--------------------------------------------------------------------------*/
#ifndef		_BOOLE_H_
#define		_BOOLE_H_

typedef int	BOOLE;		// boolean type

#define FALSE	0
#define TRUE	1

#endif
