//ids for AppBldr.hlp

#define HELPID_IDX_MENUS               001
#define HELPID_IDX_ESSENTIALS          002
#define HELPID_IDX_DATABASE            003
#define HELPID_IDX_CATEGORIES          004
#define HELPID_IDX_OBJDS               005

#define HELPID_MENU_FILE               100
#define HELPID_MENU_EDIT               101
#define HELPID_MENU_PROJECT            102
#define HELPID_MENU_SUBJECT            103
#define HELPID_MENU_OBJECT             104
#define HELPID_MENU_WINDOWS            105
#define HELPID_MENU_HELP               106

#define HELPID_FILE_NEWPROJECT         120
#define HELPID_FILE_NEWSUBJECT         121
#define HELPID_FILE_OPENPROJECT        122
#define HELPID_FILE_CLOSE              123
#define HELPID_FILE_SAVE               124
#define HELPID_FILE_SAVEAS             125
#define HELPID_FILE_IMPORT             126
#define HELPID_FILE_EXPORT             127
#define HELPID_FILE_PRINT              128
#define HELPID_FILE_PRINTSETUP         129
#define HELPID_FILE_EXIT               130

#define HELPID_EDIT_UNDO               140
#define HELPID_EDIT_CUT                141
#define HELPID_EDIT_COPY               142
#define HELPID_EDIT_PASTE              143
#define HELPID_EDIT_CLEAR              144
#define HELPID_EDIT_MOVEOBJECT         145
#define HELPID_EDIT_SELECTALL          146
#define HELPID_EDIT_SHOWSELECT         147

#define HELPID_PROJ_RUN                160
#define HELPID_PROJ_CONTINUE           161
#define HELPID_PROJ_RESET              162
#define HELPID_PROJ_CREATEAPPLICATION  163
#define HELPID_PROJ_CHECKFORERRORS     164
#define HELPID_PROJ_ARRANGEICONS       165
#define HELPID_PROJ_GRIDON             166
#define HELPID_PROJ_EDITICON           167
#define HELPID_PROJ_AUTOSAVE           168
#define HELPID_PROJ_CONFIRMSAVE        169
#define HELPID_PROJ_ENABLESTOPS        170
#define HELPID_PROJ_CLEARSTOPS         171

#define HELPID_SUBJ_CHECKFORERRORS     180
#define HELPID_SUBJ_SHOWPERSIST        181
#define HELPID_SUBJ_LARGEICON          182
#define HELPID_SUBJ_SHOWSIGNALS        183
#define HELPID_SUBJ_FUNCTIONGRID       184
#define HELPID_SUBJ_TOGGLESTOPS        185
#define HELPID_SUBJ_CLEARSTOPS         186
#define HELPID_SUBJ_NEWCOMMENT         187

#define HELPID_MOBJ_CHECKFORERRORS     200
#define HELPID_MOBJ_CHANGEPERSIST      201
#define HELPID_MOBJ_SHARE              202
#define HELPID_MOBJ_UNSHARE            203
#define HELPID_MOBJ_MAKEALIAS          204

#define HELPID_WIN_PALETTE             220
#define HELPID_WIN_NAVIGATOR           221
#define HELPID_WIN_CASCADE             222
#define HELPID_WIN_TILE                223
#define HELPID_WIN_ARRANGEICONS        224

#define HELPID_HELP_INDEX              240
#define HELPID_HELP_USINGHELP          241
#define HELPID_HELP_ABOUT              242

#define HELPID_CAT_Sysm               1001
#define HELPID_CAT_Brws               1002
#define HELPID_CAT_Bndl               1003
#define HELPID_CAT_Butn               1004
#define HELPID_CAT_Calc               1005
#define HELPID_CAT_Acur               1006
#define HELPID_CAT_Datb               1007
#define HELPID_CAT_Date               1008
#define HELPID_CAT_File               1009
#define HELPID_CAT_Flop               1010
#define HELPID_CAT_Genl               1011
#define HELPID_CAT_Grup               1012
#define HELPID_CAT_Imex               1013
#define HELPID_CAT_Keyb               1014
#define HELPID_CAT_Appl               1015
#define HELPID_CAT_List               1016
#define HELPID_CAT_Loop               1017
#define HELPID_CAT_Menu               1018
#define HELPID_CAT_Mbar               1019
#define HELPID_CAT_Mitm               1020
#define HELPID_CAT_Ntfy               1021
#define HELPID_CAT_Nmbr               1022
#define HELPID_CAT_Page               1023
#define HELPID_CAT_Pict               1024
#define HELPID_CAT_Prnt               1025
#define HELPID_CAT_Rdgp               1026
#define HELPID_CAT_Scal               1027
#define HELPID_CAT_Subr               1028
#define HELPID_CAT_Tabl               1029
#define HELPID_CAT_Text               1030
#define HELPID_CAT_Tfct               1031
#define HELPID_CAT_Time               1032
#define HELPID_CAT_Wino               1033

#define HELPID_OBJD										3000
#define HELPID_OBJD_Sysm              2001
#define HELPID_OBJD_Brws              2002
#define HELPID_OBJD_Bndl              2003
#define HELPID_OBJD_Butn              2004
#define HELPID_OBJD_Calc              2005
#define HELPID_OBJD_Acur              2006
#define HELPID_OBJD_Datb              2007
#define HELPID_OBJD_Date              2008
#define HELPID_OBJD_File              2009
#define HELPID_OBJD_Grup              2010
#define HELPID_OBJD_Imex              2011
#define HELPID_OBJD_Keyb              2012
#define HELPID_OBJD_Appl              2013
#define HELPID_OBJD_List              2014
#define HELPID_OBJD_Loop              2015
#define HELPID_OBJD_Menu              2016
#define HELPID_OBJD_Mbar              2017
#define HELPID_OBJD_Mitm              2018
#define HELPID_OBJD_Ntfy              2019
#define HELPID_OBJD_Nmbr              2020
#define HELPID_OBJD_Page              2021
#define HELPID_OBJD_Pict              2022
#define HELPID_OBJD_Prnt              2023
#define HELPID_OBJD_Rdgp              2024
#define HELPID_OBJD_Scal              2025
#define HELPID_OBJD_Scan              2026
#define HELPID_OBJD_Subr              2027
#define HELPID_OBJD_Tabl              2028
#define HELPID_OBJD_Text              2029
#define HELPID_OBJD_Tfct              2030
#define HELPID_OBJD_Time              2031
#define HELPID_OBJD_Wino              2032

#define HELPID_DLG_ALIAS              3001
#define HELPID_DLG_BMPBTN             3002

#define HELPID_OBJ_Sysm         0x5379736D
#define HELPID_FNC_fPty         0x66507479
#define HELPID_FNC_sIdl         0x7349646C
#define HELPID_FNC_mDwn         0x6D44776E
#define HELPID_FNC_tIdl         0x7449646C
#define HELPID_FNC_uPdw         0x75506477
#define HELPID_FNC_vPty         0x76507479

#define HELPID_OBJ_Brws         0x42727773
#define HELPID_FNC_bRcl         0x6252636C

#define HELPID_OBJ_Bndl         0x426E646C
#define HELPID_FNC_pBnd         0x70426E64

#define HELPID_OBJ_Butn         0x4275746E
#define HELPID_FNC_bClr         0x62436C72
#define HELPID_FNC_bDsb         0x62447362
#define HELPID_FNC_bEnb         0x62456E62
#define HELPID_FNC_bGtt         0x62477474
#define HELPID_FNC_bTst         0x62547374
#define HELPID_FNC_bSet         0x62536574
#define HELPID_FNC_bStt         0x62537474

#define HELPID_OBJ_Calc         0x43616C63
#define HELPID_FNC_cAon         0x63416F6E
#define HELPID_FNC_cAof         0x63416F66
#define HELPID_FNC_cAlc         0x63416C63
#define HELPID_FNC_cAle         0x63416C65

#define HELPID_OBJ_Acur         0x41637572
#define HELPID_FNC_aRrw         0x61527277
#define HELPID_FNC_hAnd         0x68416E64
#define HELPID_FNC_hDcr         0x68446372
#define HELPID_FNC_sHrc         0x73487263
#define HELPID_FNC_sTcr         0x73546372
#define HELPID_FNC_sPcr         0x73506372
#define HELPID_FNC_wAch         0x77416368

#define HELPID_OBJ_Datb         0x44617462
#define HELPID_FNC_dBad         0x64426164
#define HELPID_FNC_dBaf         0x64426166
#define HELPID_FNC_dBcl         0x6442636C
#define HELPID_FNC_dBcf         0x64426366
#define HELPID_FNC_dBcn         0x6442636E
#define HELPID_FNC_dBfn         0x6442666E
#define HELPID_FNC_dBdl         0x6442646C
#define HELPID_FNC_dBfe         0x64426665
#define HELPID_FNC_dBfr         0x64426672
#define HELPID_FNC_dBfi         0x64426669
#define HELPID_FNC_dBgf         0x64426766
#define HELPID_FNC_dBgn         0x6442676E
#define HELPID_FNC_dBgp         0x64426770
#define HELPID_FNC_dBgr         0x64426772
#define HELPID_FNC_dBld         0x64426C64
#define HELPID_FNC_dBlr         0x64426C72
#define HELPID_FNC_dBms         0x64426D73
#define HELPID_FNC_dBnd         0x64426E64
#define HELPID_FNC_dBof         0x64426F66
#define HELPID_FNC_dBps         0x64427073
#define HELPID_FNC_dBrf         0x64427266
#define HELPID_FNC_dBrn         0x6442726E
#define HELPID_FNC_dBrp         0x64427270
#define HELPID_FNC_dBrr         0x64427272
#define HELPID_FNC_dBri         0x64427269
#define HELPID_FNC_dBrm         0x6442726D
#define HELPID_FNC_dBsf         0x64427366
#define HELPID_FNC_dBsr         0x64427372
#define HELPID_FNC_dBsx         0x64427378
#define HELPID_FNC_dBtx         0x64427478
#define HELPID_FNC_dBul         0x6442756C
#define HELPID_FNC_dBur         0x64427572

#define HELPID_OBJ_Date         0x44617465
#define HELPID_FNC_iNdt         0x694E6474
#define HELPID_FNC_cMdt         0x634D6474
#define HELPID_FNC_cRdt         0x63526474
#define HELPID_FNC_dTdf         0x64546466
#define HELPID_FNC_dTfs         0x64546673

#define HELPID_OBJ_File         0x46696C65
#define HELPID_FNC_fFnm         0x66466E6D
#define HELPID_FNC_fLod         0x664C6F64
#define HELPID_FNC_fNew         0x664E6577
#define HELPID_FNC_fOpn         0x664F706E
#define HELPID_FNC_fSav         0x66536176
#define HELPID_FNC_fSvs         0x66537673

#define HELPID_OBJ_Grup         0x47727570
#define HELPID_FNC_gRcn         0x6752636E
#define HELPID_FNC_gRfn         0x6752666E
#define HELPID_FNC_gRgt         0x67526774
#define HELPID_FNC_gRin         0x6752696E
#define HELPID_FNC_gRrm         0x6752726D

#define HELPID_OBJ_Imex         0x496D6578
#define HELPID_FNC_iEcf         0x69456366
#define HELPID_FNC_iEce         0x69456365
#define HELPID_FNC_iEci         0x69456369
#define HELPID_FNC_iEcr         0x69456372
#define HELPID_FNC_iExr         0x69457872
#define HELPID_FNC_iEir         0x69456972
#define HELPID_FNC_iEst         0x69457374
#define HELPID_FNC_iEsp         0x69457370

#define HELPID_OBJ_Keyb         0x4B657962
#define HELPID_FNC_kYal         0x6B59616C
#define HELPID_FNC_kYcm         0x6B59636D
#define HELPID_FNC_kYcn         0x6B59636E
#define HELPID_FNC_kYof         0x6B596F66
#define HELPID_FNC_kYon         0x6B596F6E
#define HELPID_FNC_kYop         0x6B596F70
#define HELPID_FNC_kYsh         0x6B597368

#define HELPID_OBJ_Appl         0x4170706C
#define HELPID_FNC_lApp         0x6C417070
#define HELPID_FNC_sApp         0x73417070

#define HELPID_OBJ_List         0x4C697374
#define HELPID_FNC_lClr         0x6C436C72
#define HELPID_FNC_lCnt         0x6C436E74
#define HELPID_FNC_lDel         0x6C44656C
#define HELPID_FNC_lGet         0x6C476574
#define HELPID_FNC_lGsl         0x6C47736C
#define HELPID_FNC_lNew         0x6C4E6577
#define HELPID_FNC_lSet         0x6C536574
#define HELPID_FNC_lSel         0x6C53656C
#define HELPID_FNC_lSrt         0x6C537274

#define HELPID_OBJ_Loop         0x4C6F6F70
#define HELPID_FNC_lAbt         0x6C416274
#define HELPID_FNC_lStt          0x6C537474

#define HELPID_OBJ_Menu         0x4D656E75
#define HELPID_FNC_mCnt         0x6D436E74
#define HELPID_FNC_mDel         0x6D44656C
#define HELPID_FNC_mDsb         0x6D447362
#define HELPID_FNC_mEnb         0x6D456E62
#define HELPID_FNC_mGit         0x6D476974
#define HELPID_FNC_mGpp         0x6D477070
#define HELPID_FNC_mIns         0x6D496E73
#define HELPID_FNC_mRtl         0x6D52746C
#define HELPID_FNC_mSpp         0x6D537070

#define HELPID_OBJ_Mbar         0x4D626172
#define HELPID_FNC_mBds         0x6D426473
#define HELPID_FNC_mBen         0x6D42656E
#define HELPID_FNC_mBhd         0x6D426864
#define HELPID_FNC_mBin         0x6D42696E
#define HELPID_FNC_mBsh         0x6D427368

#define HELPID_OBJ_Mitm         0x4D69746D
#define HELPID_FNC_mIds         0x6D496473
#define HELPID_FNC_mIen         0x6D49656E
#define HELPID_FNC_mItf         0x6D497466
#define HELPID_FNC_mItn         0x6D49746E

#define HELPID_OBJ_Ntfy         0x4E746679
#define HELPID_FNC_nAlt         0x6E416C74
#define HELPID_FNC_nStt         0x6E537474
#define HELPID_FNC_nStp         0x6E537470

#define HELPID_OBJ_Nmbr         0x4E6D6272
#define HELPID_FNC_nAdd         0x6E416464
#define HELPID_FNC_nCmp         0x6E436D70
#define HELPID_FNC_nDec         0x6E446563
#define HELPID_FNC_nDiv         0x6E446976
#define HELPID_FNC_nExp         0x6E457870
#define HELPID_FNC_nInc         0x6E496E63
#define HELPID_FNC_nMul         0x6E4D756C
#define HELPID_FNC_nFsz         0x6E46737A
#define HELPID_FNC_nRnd         0x6E526E64
#define HELPID_FNC_nRnz         0x6E526E7A
#define HELPID_FNC_nSub         0x6E537562

#define HELPID_OBJ_Page         0x50616765
#define HELPID_FNC_pGcl         0x7047636C
#define HELPID_FNC_pGcn         0x7047636E
#define HELPID_FNC_pGnw         0x70476E77
#define HELPID_FNC_pGsw         0x70477377

#define HELPID_OBJ_Pict         0x50696374
#define HELPID_FNC_lPct         0x6C506374
#define HELPID_FNC_sPct         0x73506374

#define HELPID_OBJ_Prnt         0x50726E74
#define HELPID_FNC_pRjb         0x70526A62
#define HELPID_FNC_pRpg         0x70527067
#define HELPID_FNC_pRob         0x70526F62
#define HELPID_FNC_pRon         0x70526F6E

#define HELPID_OBJ_Rdgp         0x52646770

#define HELPID_OBJ_Scal         0x4469616C

#define HELPID_OBJ_Scan         0x5363616E
#define HELPID_FNC_sCns         0x73436E73
#define HELPID_FNC_sCnt         0x73436E74

#define HELPID_OBJ_Subr         0x53756272
#define HELPID_FNC_cAls         0x63416C73
#define HELPID_FNC_ftCp         0x66744370
#define HELPID_FNC_rTfs         0x72546673

#define HELPID_OBJ_Tabl         0x5461626C
#define HELPID_FNC_tBat         0x74426174
#define HELPID_FNC_tBcl         0x7442636C
#define HELPID_FNC_tBac         0x74426163
#define HELPID_FNC_tBar         0x74426172
#define HELPID_FNC_tBec         0x74426563
#define HELPID_FNC_tBcs         0x74426373
#define HELPID_FNC_tBcp         0x74426370
#define HELPID_FNC_tBcr         0x74426372
#define HELPID_FNC_tBdr         0x74426472
#define HELPID_FNC_tBgc         0x74426763
#define HELPID_FNC_tBgr         0x74426772
#define HELPID_FNC_tBgs         0x74426773
#define HELPID_FNC_tBrp         0x74427270
#define HELPID_FNC_tBsc         0x74427363
#define HELPID_FNC_tBse         0x74427365
#define HELPID_FNC_tBss         0x74427373
#define HELPID_FNC_tBnc         0x74426E63
#define HELPID_FNC_tBsr         0x74427372
#define HELPID_FNC_tBst         0x74427374
#define HELPID_FNC_tBua         0x74427561


#define HELPID_OBJ_Text         0x54657874
#define HELPID_FNC_tXar         0x74586172
#define HELPID_FNC_tXat         0x74586174
#define HELPID_FNC_tXcl         0x7458636C
#define HELPID_FNC_tXcm         0x7458636D
#define HELPID_FNC_tXcn         0x7458636E
#define HELPID_FNC_tXfr         0x74586672
#define HELPID_FNC_tXgf         0x74586766
#define HELPID_FNC_tXgl         0x7458676C
#define HELPID_FNC_tXgn         0x7458676E
#define HELPID_FNC_tXgw         0x74586777
#define HELPID_FNC_tXit         0x74586974
#define HELPID_FNC_tXls         0x74586C73
#define HELPID_FNC_tXlt         0x74586C74
#define HELPID_FNC_tXms         0x74586D73
#define HELPID_FNC_tXrs         0x74587273
#define HELPID_FNC_tXst         0x74587374
#define HELPID_FNC_tXfs         0x74586673
#define HELPID_FNC_tXln         0x74586C6E
#define HELPID_FNC_tXuc         0x74587563

#define HELPID_OBJ_Tfct         0x54666374
#define HELPID_FNC_tAon         0x74416F6E
#define HELPID_FNC_tAof         0x74416F66
#define HELPID_FNC_tFcl         0x7446636C
#define HELPID_FNC_tFst         0x74467374

#define HELPID_OBJ_Time         0x54696D65
#define HELPID_FNC_tIin         0x7449696E
#define HELPID_FNC_tIcm         0x7449636D
#define HELPID_FNC_tIcs         0x74496373
#define HELPID_FNC_tIcr         0x74496372
#define HELPID_FNC_tIdf         0x74496466
#define HELPID_FNC_tIfs         0x74496673

#define HELPID_OBJ_Wino         0x57696E6F
#define HELPID_FNC_iAct         0x69416374
#define HELPID_FNC_aCti         0x61437469
#define HELPID_FNC_cCls         0x63436C73
#define HELPID_FNC_cNtw         0x634E7477
#define HELPID_FNC_cLsw         0x634C7377
#define HELPID_FNC_fRtw         0x66527477
#define HELPID_FNC_gWtl         0x6757746C
#define HELPID_FNC_hItm         0x6849746D
#define HELPID_FNC_iSwo         0x6953776F
#define HELPID_FNC_iTml         0x69546D6C
#define HELPID_FNC_mSlc         0x6D536C63
#define HELPID_FNC_mVit         0x6D566974
#define HELPID_FNC_mOvw         0x6D4F7677
#define HELPID_FNC_oPnw         0x6F506E77
#define HELPID_FNC_sWtl         0x7357746C
#define HELPID_FNC_sItm         0x7349746D
#define HELPID_FNC_sIzw         0x73497A77

#define HELPID_FNC_aSin         0x6153696E
#define HELPID_FNC_bEep         0x62456570
#define HELPID_FNC_cOpy         0x634F7079
#define HELPID_FNC_cUtt         0x63557474
#define HELPID_FNC_dLay         0x644C6179
#define HELPID_FNC_dIal         0x6449616C
#define HELPID_FNC_fRem         0x6652656D
#define HELPID_FNC_cLrn         0x634C726E
#define HELPID_FNC_sMob         0x734D6F62
#define HELPID_FNC_sMot         0x734D6F74
#define HELPID_FNC_pAst         0x70417374
#define HELPID_FNC_qUit         0x71556974
#define HELPID_FNC_uNdo         0x754E646F
#define HELPID_FNC_ySnc         0x79536E63

#define HELPID_FNC_fOcf         0x664F6366
#define HELPID_FNC_fOcp         0x664F6370
#define HELPID_FNC_fOdl         0x664F646C
#define HELPID_FNC_fOdr         0x664F6472
#define HELPID_FNC_fOdn         0x664F646E
#define HELPID_FNC_fOnf         0x664F6E66
#define HELPID_FNC_fOpt         0x664F7074
