/***********************************************************************
		CURSORDL.H
	 	Defines for cursor dlg box
************************************************************************/
#define FRAMECOUNTID		460
#define ID_TEST					-12
#define ID_OBJECT				-10
#define ID_GROUP  			-11

#define ID_BORDER				136


#define TABLEDLG        1000
#define TABLEFONT       1001
#define CURSORDG        1002

#define BASEID          300
#define CONSTATICID			301
#define TYPESTATICID		302
#define OBJECTSTATICID	303
#define WIDTHSTATICID		304
#define PIXELSTATICID		305
#define WIDTHID         306
#define ITEMSTYLEID     307
#define TITLESTYLEID    308
#define LEFTID          309
#define RIGHTID         310
#define CENTERID        311
#define AREMOVEID      	312
#define ATYPEID         314
#define AOBJECTID       315
#define ATITLEID        316
#define TITLESTATICID   317

#define AIDOK           1
#define AIDCANCEL       2
#define ACOLUMNID       200
#define ASTATICID       201
#define ANEWID          202

#define AUTOFILLID      114
#define MULTIPLEID      115
#define SHOWTITLEID     116
#define COLLINESID      117
#define ROWLINESID      118
#define ROWINDEXID      119
#define HSCROLLID       120
#define VSCROLLID       121
#define BLANKCORNERID   122
#define ACTIVATEID      123
#define TMPID           124
#define ITALICID        126
#define ULINEID         127
#define OUTLINEID       128
#define SHADOWID        129
#define BOLDID          131
#define DEFAULTBOXID    132
#define FONTID          133
#define SIZEID          134

#define IDHELP					135

#define DELAYID	        450
#define FRAMEID	        451
#define ICONEDIT        452
#define COLOREDIT       453
#define BWEDIT          454
#define DELICONID       455
#define LOADICONID      456
#define NEWID           457
#define HELPID          458
#define CLEARID         459

#define IDC_HAND        500




