////////////////////////////////////////////////////////////////////////////
//	This file contains the defines for menu item and control ids.
////////////////////////////////////////////////////////////////////////////

#ifndef __RESCONST_H__
#define __RESCONST_H__

// defines for items in the "File" popup

#define IDM_NEWPROJECT		100
#define IDM_NEWSUBJECT		101
#define IDM_OPEN			102
#define IDM_CLOSE			103
#define IDM_SAVE			104
#define IDM_SAVEAS			105
#define IDM_PAGESETUP		106
#define IDM_PRINT			107
#define IDM_PRINTSTORY		108
#define IDM_DELETE			109
#define IDM_QUIT			110

// defines for items in the "Edit" popup

#define IDM_UNDOUNDO				120
#define IDM_CUT             121
#define IDM_COPY            122
#define IDM_PASTE           123
#define IDM_CLEAR           124
#define IDM_PUBLISH         125
#define IDM_SUBSCRIBE       126
#define IDM_SELECTALL       127
#define IDM_SHOWSELECT      128

// defines for items in the "Project" popup

#define IDM_ARRANGESUBJECTS 130
#define IDM_PROJECTGRID     132
#define IDM_EDITICON				131

// defines for items in the "Subject" popup

#define IDM_SKETCH				140
#define IDM_OBJECTALK			141
#define IDM_SUBJERRORS		142
#define IDM_OBJERRORS			143
#define IDM_CHANGEPERSIST	144
#define IDM_SHOWPERSIST		145
#define IDM_LARGEICONS		146
#define IDM_FUNCGRID			147
#define IDM_ACCURACY			148
#define IDM_COMMENT				149
#define IDM_ZOOMFUNCWIN   150

// defines for items in the "Window" popup

#define IDM_PALETTE			160
#define IDM_NAVIGATOR		161
#define	IDM_CASCADE     162
#define IDM_TILE        163
#define IDM_ARRANGE     164

// defines for items in the "Help" popup

#define	IDM_HELP_INDEX		170
#define	IDM_TOPIC_SEARCH	171
#define	IDM_USING_HELP		172
#define IDM_ABOUT					173

// defines for the icon editor menu

#define IDM_SAVEICON		201
#define IDM_CLEARICON   202
#define IDM_RESTOREICON 203
#define IDM_IMPORT      204

// other defines


#define IDM_FIRSTCHILD	300

#define ID_NEWNAME		104
#define ID_STATICTEXT	106

#define ID_OK			100
#define ID_CANCEL		102

#define ID_BCOMMENT 104
#define ID_FCOMMENT 106

// defines for string resources

#define STR_FRAMENAME	211
#define STR_PROJECTNAME	212
#define STR_SUBJECTNAME 213
#define STR_NAVIGATOR	214

#define PALETTEHEIGHT 91
#define SUBJECT_NAME_LENGTH 32

#endif
