#define  idx_contents		1000
#define  idx_introduction_to_the_window_alm		0x57696E6F	/*Wino*/
#define  idx_editing_the_window_layout		1002
#define  idx_sizing_and_positioning_a_window		1003
#define  idx_adding_and_removing_objects		1004
#define  idx_creating_new_objects		1005
#define  idx_renaming_objects		1006
#define  idx_editing_objects		1007
#define  idx_sizing_and_positioning_window_items		1008
#define  idx_editing_the_window_attributes_dialog		3000
#define  idx_adding_a_menu_bar		1010
#define  idx_naming_the_window		1011
#define  idx_setting_window_options_windows		1012
#define  idx_selecting_a_window_style__macintosh		1013
#define  idx_editing_the_window_sizes_dialog		3001
#define  idx_specifying_the_startup_location		1015
#define  idx_specifying_minimum_and_maximum_size		1016
#define  idx_specifying_the_scroll_area		1017
#define  idx_editing_the_preferences_dialog__windows		3002
#define  idx_editing_the_select_items_dialog__macintosh		1019
#define  idx_the_attach_dialog		3003
#define  idx_default_effect		1021
#define  idx_vertical_increase		1022
#define  idx_right_increase		1023
#define  idx_right_and_vertical_increase		1024
#define  idx_fixed_vertical_distance		1025
#define  idx_right_increase__fixed_vertical_distance		1026
#define  idx_fixed_horizontal_distance		1027
#define  idx_vertical_increase__fixed_horizontal		1028
#define  idx_fixed_horizontal_and_vertical_distance		1029
#define  idx_the_on_resize_dialog		1030
#define  idx_the_palettes		7000
#define  idx_the_tools_palette		1032
#define  idx_selection_tool_nonscroll		4000
#define  idx_reorder_tool_nonscroll		4001
#define  idx_tab_stops_tool_nonscroll		4002
#define  idx_group_stops_tool_nonscroll		4003
#define  idx_visibility_tool_nonscroll		4004
#define  idx_lock_tool_nonscroll			4005
#define  idx_attach_tool_nonscroll			4006
#define  idx_group_box_tool_nonscroll		4007
#define  idx_select_all_tool_nonscroll		4008
#define  idx_background_tool_nonscroll		4009
#define  idx_foreground_background_color_select		1045
#define  idx_oval_tools_nonscroll		4010
#define  idx_box_tools_nonscroll		4011
#define  idx_rounded_box_tools_nonscroll		4012
#define  idx_line_tool_nonscroll		4013
#define  idx_text_tool_nonscroll		4014
#define  idx_line_select_tool_nonscroll		4015
#define  idx_pattern_color_tool_nonscroll		4016
#define  idx_pattern_select_tool__macintosh		1053
#define  idx_font_selection_tool_nonscroll		4017
#define  idx_the_position_palette		1055
#define  idx_the_object_list_palette		1061
#define  idx_the_sizes_palette__macintosh		1062
#define  idx_window_layout_menus		6000
#define  idx_file_menu		1064
#define  idx_edit_menu		1065
#define  idx_view_menu		1234
#define  idx_alignment_menu		1066
#define  idx_items_menu		1067
#define  idx_color_layouts_versus_black_and_white		1068
#define  idx_tools_menu		1069
#define  idx_palettes_menu		1070
#define  idx_style_menu__macintosh		1071
#define  idx_window_object_signals		1072
#define  idx_window_alm_functions		1073
#define  idx_activate_item			0x69416374	/*iAct*/
#define  idx_active_item			0x61437469	/*aCti*/
#define  idx_cancel_close			0x63436C73	/*cCls*/
#define  idx_center_window		0x634E7477	/*cNtw*/
#define  idx_close_window		0x634C7377	/*cLsw*/
#define  idx_disable_move_items		1079
#define  idx_enable_move_items		1080
#define  idx_front_window		0x66527477	/*fRtw*/
#define  idx_get_item_selection		0x67576973	/*gWis*/
#define  idx_get_title			0x6757746C	/*gWtl*/
#define  idx_hide_item			0x6849746D	/*hItm*/
#define  idx_item_location			0x69546D6C	/*iTml*/
#define  idx_mouse_location		0x6D536C63	/*mSlc*/
#define  idx_move_item			0x6D566974	/*mVit*/
#define  idx_move_window		0x6D4F7677	/*mOvw*/
#define  idx_open_window		0x6F506E77	/*oPnw*/
#define  idx_set_item_selection		0x73576973	/*sWis*/
#define  idx_set_title			0x7357746C	/*sWtl*/
#define  idx_show_item			0x7349746D	/*sItm*/
#define  idx_size_window			0x73497A77	/*sIzw*/
#define  idx_start_modal		1094
#define  idx_stop_modal		1095
#define  idx_transition		1096
#define  idx_window_open		0x6953776F	/*iSwo*/
#define  idx_window_position		0x67577073	/*gWps*/
#define  idx_setting_window_options__macintosh		1099
#define  idx_font_menu__macintosh		1101
#define  idx_align_left_nonscroll			5000
#define  idx_align_right_nonscroll			5001
#define  idx_align_top_nonscroll			5002
#define  idx_align_bottom_nonscroll		5003
#define  idx_center_group_horizontally_nonscroll	5004
#define  idx_center_group_vertically_nonscroll	5005
#define  idx_center_horizontally_nonscroll		5006
#define  idx_center_vertically_nonscroll		5007
#define  idx_grow_to_widest_nonscroll		5008
#define  idx_shrink_to_thinnest_nonscroll		5009
#define  idx_grow_to_tallest_nonscroll		5010
#define  idx_shrink_to_shortest_nonscroll		5011
#define  idx_space_vertically_nonscroll		5012
#define  idx_space_horizontally_nonscroll		5013
#define  idx_usage_activate_item		1119
#define  idx_usage_active_item		1122
#define  idx_usage_cancel_close		1125
#define  idx_usage_center_window		1128
#define  idx_usage_close_window		1131
#define  idx_disable_item_input		1133
#define  idx_enable_item_input		1136
#define  idx_usage_disable_move_items		1138
#define  idx_usage_get_item_selection		1148
#define  idx_usage_item_location		1155
#define  idx_usage_move_item		1160
#define  idx_usage_move_window		1163
#define  idx_usage_open_window		1166
#define  idx_usage_set_item_selection		1169
#define  idx_usage_start_modal		1179
#define  idx_usage_transition		1184
#define  idx_push_effects		1185
#define  idx_wipe_effects		1186
#define  idx_frame_effects		1187
#define  idx_circle_effects		1188
#define  idx_dissolve_effects		1189
#define  idx_usage_window_position		1195
#define  idx_group_box_tool_macintosh		1197
#define  idx_oval_tools_macintosh		1198
#define  idx_box_tools_macintosh		1199
#define  idx_rounded_box_tools_macintosh		1200
#define  idx_line_tool_macintosh		1201
#define  idx_text_tool_macintosh		1202
#define  idx_line_select_tool_macintosh		1203
#define  idx_selection_tool		1204
#define  idx_reorder_tool__windows		1205
#define  idx_tab_stops_tool__windows		1206
#define  idx_group_stops_tool__windows		1207
#define  idx_visibility_tool__windows		1208
#define  idx_lock_tool__windows		1209
#define  idx_attach_tool__windows		1210
#define  idx_group_box_tool_windows		1211
#define  idx_select_all_tool__windows		1212
#define  idx_background_tool__windows		1213
#define  idx_oval_tools_windows		1214
#define  idx_box_tools_windows		1215
#define  idx_rounded_box_tools_windows		1216
#define  idx_align_left		1217
#define  idx_align_right		1218
#define  idx_align_top		1219
#define  idx_align_bottom		1220
#define  idx_center_group_horizontally		1221
#define  idx_space_horizontally		1224
#define  idx_space_vertically		1225
#define  idx_shrink_to_shortest		1226
#define  idx_grow_to_tallest		1227
#define  idx_shrink_to_thinnest		1228
#define  idx_grow_to_widest		1229
#define  idx_center_vertically		1230
#define  idx_center_horizontally		1231
#define  idx_center_group_vertically		1232
#define  idx_font_selection_tool__windows		1233
#define  idx_help_menu		1235
