#ifndef _MENUDLG_H_
#define _MENUDLG_H_


long EditMenuObject(
  OBJECTID  objID);

#define BTN_ADD            101
#define BTN_REMOVE         102
#define BTN_EDIT           119
#define BTN_SEPARATOR      103

#define BTN_DISPLAYNAME    104
#define BTN_DISPLAYTITLE   105

#define BTN_NORMAL         106
#define BTN_POPUP          107

#define BTN_ENABLED        110
#define BTN_DISABLED       111

#define BTN_SHOWITEMS      118
#define BTN_SHOWMENUS      117

#define LB_SOURCE          116
#define LB_DESTINATION     115

#define SLE_TITLE          112

#define CB_TEXTTO          113
#define CB_INDEXTO         114

#define IDHELP             999

#define IDD_OBJECT         201


#define SEPARATORID        (-2)
#define BLANKID            (-3)

#define SEPARATORTEXT      "------------------------------------"

#endif
