#ifndef DIALOG_H
#define DIALOG_H

#define POLYBUTTON_MAIN_SETUP_DIALOG			100
#define BUTTON_CONFIG_DIALOG							101

#define PB_OK               1
#define PB_CANCEL           2
#define PB_HELP							3
#define PB_DELETE						4

#define PB_CONFIGURE				100
#define PB_LOAD							101
#define PB_PASTE						102

#define RB_NORMAL						110
#define RB_HIGHLIGHT				111

#define RB_TOOL_ARROW				120
#define RB_TOOL_RECT				121
#define RB_TOOL_ELLIPSE			122
#define RB_TOOL_POLYGON			123
#define RB_TOOL_FREEHAND		124

#define RB_PUSH							130
#define RB_RADIO						131
#define RB_CHECK						132
#define RB_TRANSPARENT			133
#define ED_TITLE						134

#define ST_REGION_NUMBER		140
#define ST_OBJECTNAME				141
#define ST_VERTLINE					142
#define ST_HORZLINE					143

#define OD_FRAME						150
#define OD_DRAWWINDOW				151

#define AC_DELETE        		160

#endif



