#ifndef N_DIALOG_H
#define N_DIALOG_H


/// Define for dialog ID's ////

#define NUMBER_SETUP_DIALOG		100

#define ST_OBJECTNAME				1001  //The name of the object type being edited

/// Defines for controls ////
#define ED_TITLE						1100
#define PB_OK               1
#define PB_CANCEL           2
#define PB_HELP							3

#define CB_FRAME		        1302
#define RB_LEFT             1305
#define RB_RIGHT            1307
#define PB_FONTS						1312
#define PB_COLOR						1313
#define CB_SELECTALL				1316
#define CB_DISPLAYEMPTY			1320
#define RB_NOTACTIVATE	1102
#define RB_ACTIVATEONLY	1103
#define RB_ACTIVATEEDIT	1104

#define RB_INUMBER					1400
#define RB_RNUMBER					1401
#define ED_FORMAT						1403
#define ST_FORMAT						1404
#endif

