#define  idx_contents		1000
#define  idx_introduction_to_the_group_alm		0x47727570	/*Grup*/
#define  idx_editing_the_group_object		3000
#define  idx_group_object_signals		1003
#define  idx_group_functions		1004
#define  idx_adding_and_removing_objects	1005
#define  idx_editing_objects_in_the_group	1006
#define  idx_count_objects				0x6752636E	/*gRcn*/
#define  idx_find_object					0x6752666E	/*gRfn*/
#define  idx_get_object					0x67526774	/*gRgt*/
#define  idx_insert_object					0x6752696E	/*gRin*/
#define  idx_remove_object				0x6752726D	/*gRrm*/

